import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main sidebar with all documentation
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // User Guide sidebar
  userGuideSidebar: [
    {
      type: "autogenerated",
      dirName: "user-guide",
    },
  ],

  // System Admin Guide sidebar  
  systemAdminGuideSidebar: [
    {
      type: "autogenerated",
      dirName: "system-admin-guide", 
    },
  ],

  // Developer Guide sidebar
  developerGuideSidebar: [
    {
      type: "autogenerated", 
      dirName: "developer-guide",
    },
  ],
};

export default sidebars;
